// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH0psBctMOaDTfBYc_qbbsp_S4j7wEYRY',
    appId: '1:327170268263:web:37bab34546bb468f1b88c2',
    messagingSenderId: '327170268263',
    projectId: 'myapp-f48d2',
    authDomain: 'myapp-f48d2.firebaseapp.com',
    storageBucket: 'myapp-f48d2.firebasestorage.app',
    measurementId: 'G-NN061CNZFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Nz7VQ2TV146sP9MM1Q_OORQ538vouaA',
    appId: '1:327170268263:android:3f01ac14dc5c8ea61b88c2',
    messagingSenderId: '327170268263',
    projectId: 'myapp-f48d2',
    storageBucket: 'myapp-f48d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQa7puos0LRheND_UiaPUcomRa0VaZTgs',
    appId: '1:327170268263:ios:01109ee17099c4a91b88c2',
    messagingSenderId: '327170268263',
    projectId: 'myapp-f48d2',
    storageBucket: 'myapp-f48d2.firebasestorage.app',
    iosClientId: '327170268263-ntfpkvq5pva0lu903p2acfcss99ghrjc.apps.googleusercontent.com',
    iosBundleId: 'com.smartsakhiexample.smartSakhiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH0psBctMOaDTfBYc_qbbsp_S4j7wEYRY',
    appId: '1:327170268263:web:933d6d9ff58f614f1b88c2',
    messagingSenderId: '327170268263',
    projectId: 'myapp-f48d2',
    authDomain: 'myapp-f48d2.firebaseapp.com',
    storageBucket: 'myapp-f48d2.firebasestorage.app',
    measurementId: 'G-4GYQ3EGTHS',
  );
}
